name: 🐞 Bug Report
description: File a bug report here
title: "[BUG]: "
labels: ["bug, triage"]
assignees: ["haolamnm"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Before you submit, please search the existing issues to see if your bug has already been reported. If it has, please add any additional information you have to the existing issue.

  - type: checkboxes
    id: new-bug
    attributes:
      label: Is there an existing issue for this?
      description: |
        Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Description of the bug
      description: Give me a brief description of what happened and what should have happened.
      placeholder: |
        Ex. When I do '...', I expect '...' to happen, but instead '...' happens. This is a problem because '...'.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Provide details about the environment in which the bug occurred. (e.g. operating system, browser, version, etc.)
      placeholder: |
        Ex. OS: Windows 11, Browser: Chrome.
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: |
        Provide any additional information such as logs, screenshots, likes, scenarios in which the bug occurs so that it facilitates resolving the issue.
      placeholder: |
        Ex. I have attached a screenshot of the error message. I have also checked the logs and found the following error message. The bug occurs only when I do '...'.
    validations:
      required: false

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: |
        How can we get in touch with you if we need more info?
      placeholder: |
        Ex. email@example.com
    validations:
      required: false
